### ISSUE TITLE
Add binding to execute current cell

### ISSUE THREAD

**Issue by jpambrun** [HansKre/markdown-execute#1]
The "execute command in terminal" well fine, but I don't want to touch the mouse. Is there any way to add a binding to execute the entire markdown cell where the cursor is?

**Comment by HansKre** [comment]
Hi @jpambrun 

According to documentation:

> Alternatively, use `cmd+f1` (mac) / `ctrl+f1` (windows) shortcut to execute current selection.

Did you try that?

**Comment by jpambrun** [comment]
I am not 100% sure since Ctrl+F1 doesn't work for me, see #3, but my
understanding it that it first requires to select the text and choose a
runtime. I want a shortcut that run the block where the cursur is and the
runtime be determined by the markdown block syntax, just like when I press
the action button.

**Comment by HansKre** [comment]
Hi @jpambrun, I implemented a logic for that. There are 3 cases to consider:

1. cursor is at opening backticks of a codeblock
2. cursor is at closing backticks of a codeblock
3. cursor is somewhere inbetween

For first tow cases, the codeblock inbetween is selected, runtime is detected and codeblock is exectued.
For the third case, I saw two different approaches: one would have been to try to go up and down from cursor-position and try to expand the selection. Another, also valid approach is to execute exactly the line at the cursor. From a user perspective, I found both to be pefectly valid approaches, but the last one significantly easier to implement, which is why it is the one that I chose.
